--1.
SELECT gv.MAGV,gv.HODEM,gv.TEN
FROM GIAOVIEN AS gv 
	JOIN LOPHOCPHAN_GIAOVIEN AS lg ON gv.MAGV = lg.MAGV
	JOIN LOPHOCPHAN AS l ON lg.MALOPHOCPHAN = l.MALOPHOCPHAN
WHERE l.TENLOPHOCPHAN= N'Nói 2 - Nhóm 3'
--2.
SELECT gv.MAGV,gv.HODEM,gv.TEN
FROM GIAOVIEN AS gv
	 JOIN LOPHOCPHAN_GIAOVIEN AS lg ON gv.MAGV = lg.MAGV
	 JOIN LOPHOCPHAN AS l ON lg.MALOPHOCPHAN = l.MALOPHOCPHAN
 WHERE l.TENLOPHOCPHAN= N'Ngữ pháp-Nhóm 1'

--3.
SELECT sv.HODEM,sv.TEN,sv.MASINHVIEN,ld.DIEMTHI
FROM SINHVIEN AS sv 
	JOIN LOPHOCPHAN_SINHVIEN AS ls ON sv.MASINHVIEN =  ls.MASINHVIEN
	JOIN LOPHOCPHAN_DIEMTHI AS ld ON ls.MASINHVIEN = ld.MASINHVIEN 
WHERE ld.DIEMTHI > 8               
--4.
SELECT sv.MASINHVIEN,sv.HODEM,sv.TEN
FROM SINHVIEN AS sv 
	JOIN LOPHOCPHAN_SINHVIEN AS ls ON sv.MASINHVIEN = ls.MASINHVIEN
	JOIN LOPHOCPHAN AS l ON ls.MALOPHOCPHAN = l.MALOPHOCPHAN
WHERE l.TENLOPHOCPHAN = N' Nói 1-Nhóm 3'	
--5.
SELECT sv.HODEM,sv.TEN,sv.MASINHVIEN
FROM SINHVIEN AS sv 
WHERE sv.NOISINH = N'Huế'