--1.Hãy thống kee xem mỗi một loại chứng chỉ hiện đã mở được bao nhiêu lớp
SELECT c.MACHUNGCHI,c.TENCHUNGCHI,
COUNT(l.MALOP) AS SOLOP
FROM CHUNGCHI AS c
	LEFT JOIN LOPHOC AS l ON c.MACHUNGCHI=l.MACHUNGCHI
GROUP BY c.MACHUNGCHI,c.TENCHUNGCHI
--2.Hãy thống kê xem mỗi loại chứng chỉ hiện đã mở được bao nhiêu lớp và đã 
--có bao nhiêu lượt học viên đăng kí
SELECT c.TENCHUNGCHI,hl.NGAYGHIDANH,
COUNT(DISTINCT l.MALOP) AS SOLOP,
COUNT(hl.MAHOCVIEN) AS LUOTDANGKI
FROM CHUNGCHI AS c
	LEFT JOIN LOPHOC AS l ON c.MACHUNGCHI = l.MACHUNGCHI
	LEFT JOIN HOCVIEN_LOPHOC AS hl ON l.MALOP = hl.MALOP
GROUP BY c.TENCHUNGCHI,hl.NGAYGHIDANH
--3.Hãy thống kê xem trong tháng 9 năm 2010 mỗi một 
--chứng chỉ có bao nhiêu lượt học viên đăng ký học.
SELECT c.MACHUNGCHI,c.TENCHUNGCHI,
COUNT(hl.MAHOCVIEN) AS LUOTDANGKI
FROM CHUNGCHI AS c
	LEFT JOIN LOPHOC AS l ON c.MACHUNGCHI = l.MACHUNGCHI
	LEFT JOIN HOCVIEN_LOPHOC AS hl ON l.MALOP = hl.MALOP
		AND MONTH(hl.NGAYGHIDANH)= 9
		AND YEAR(hl.NGAYGHIDANH)= 2010
GROUP BY c.MACHUNGCHI,c.TENCHUNGCHI
--4.Tổng số tiền học phí mà mỗi lớp dự kiến sẽ thu được là bao nhiêu?
SELECT l.MALOP,l.TENLOP,l.HOCPHI,
	l.HOCPHI * COUNT(hl.MAHOCVIEN) AS TONGDUNG,
	SUM(l.HOCPHI) AS TONGSAI
FROM LOPHOC AS l
	LEFT JOIN HOCVIEN_LOPHOC AS hl ON l.MALOP = hl.MALOP
GROUP BY l.MALOP,l.TENLOP,l.HOCPHI
--5.Tổng số tiền học phí mà mỗi lớp đã thu được là bao nhiêu?
SELECT l.MALOP,l.TENLOP,pt.SOTIENNOP,
SUM(pt.SOTIENNOP) AS TONGTIENTHUDUOC
FROM LOPHOC AS l
	LEFT JOIN HOCVIEN_LOPHOC AS hl ON l.MALOP = hl.MALOP
	LEFT JOIN PHIEUTHUHOCPHI AS pt ON hl.MALOP = pt.MALOP
GROUP BY l.MALOP,l.TENLOP,pt.SOTIENNOP
--6.Những học viên nào đã nộp tiền học phí với tổng số 
--tiền lớn hơn 1 triệu đồng? Là đã nộp bao nhiêu tiền?
SELECT hv.MAHOCVIEN,hv.HOTEN,pt.SOTIENNOP,
SUM(pt.SOTIENNOP) AS TONGTIEN
FROM HOCVIEN AS hv 
	LEFT JOIN PHIEUTHUHOCPHI AS pt ON hv.MAHOCVIEN =pt.MAHOCVIEN
GROUP BY hv.MAHOCVIEN,hv.HOTEN,pt.SOTIENNOP



