SELECT H.MAHANG, H.TENHANG, H.DONVITINH , H.GIAHANG
FROM MATHANG AS H
SELECT KH.TENCONGTY, KH.TENGIAODICH, KH.EMAIL, KH.DIENTHOAI
FROM KHACHHANG AS KH
SELECT MAHANG, TENHANG, GIAHANG
FROM MATHANG 
SELECT NV.MANHANVIEN, NV.HO, NV.TEN, NV.NGAYSINH, 
YEAR(GETDATE()) - YEAR(NV.NGAYSINH) AS TUOI
FROM NHANVIEN AS NV 
SELECT NV.MANHANVIEN, NV.HO, NV.TEN,NV.NGAYLAMVIEC,
 (YEAR(GETDATE()) - YEAR( NV.NGAYLAMVIEC) * 12 ) AS SOTHANGLAMVIEC
FROM	NHANVIEN AS NV
SELECT NV.NGAYSINH, NV.NGAYLAMVIEC,
YEAR(NV.NGAYLAMVIEC) -  YEAR ( NV.NGAYSINH) AS TUOIBATDAULAMVIEC
FROM NHANVIEN AS NV
SELECT DISTINCT LUONGCOBAN
FROM NHANVIEN
SELECT DISTINCT DONVITINH
FROM MATHANG
SELECT NV.MANHANVIEN, NV.HO,NV.TEN, NV.LUONGCOBAN,
CASE
		 WHEN	 NV.LUONGCOBAN <=1500 THEN 500
		 WHEN ( NV.LUONGCOBAN >= 1500 AND NV.LUONGCOBAN < =3000 ) THEN  800
	ELSE 1000
END AS TIENTHUONGTET
FROM NHANVIEN AS NV
SELECT NV.MANHANVIEN , NV.HO,NV.TEN, NV.NGAYLAMVIEC, YEAR(GETDATE())- (NV.NGAYLAMVIEC) AS SONGAYLAMVIEC
CASE
			WHEN YEAR(GETDATE()) - YEAR(NV.NGAYLAMVIEC) < 10 THEN 1000
			WHEN(YEAR(GETDATE()) - YEAR(NV.NGAYLAMVIEC) >=10 )AND (YEAR(GETDATE()) - YEAR(NV.NGAYLAMVIEC) <20 ) THEN 2000
			WHEN (YEAR(GETDATE()) - YEAR(NV.NGAYLAMVIEC) >=20 ) AND (YEAR(GETDATE()) - YEAR(NV.NGAYLAMVIEC) <=25) THEN 3000
ELSE 5000
  END AS TIENTHUONGTRIAN
  ORDER BY TIENTHUONGTRIAN DESC
 FROM NHANVIEN AS NV
 SELECT M.MAHANG, M.TENHANG, M.DONVITINH, M.GIAHANG
 FROM MATHANG AS M
 WHERE GIAHANG > 100000
 SELECT M.SOLUONG
 FROM MATHANG AS M
 WHERE ( M.SOLUONG >= 200 AND M.SOLUONG <=500)
 









